### ISSUE TITLE
Better handling of formula/python float results

### ISSUE THREAD

**Issue by davidfig** [quadratichq/quadratic#1086]
Currently, if you do a calculation that results in a float output for Formula, it will sometimes have a floating-point issue, eg, `10.1 + 1 = 11.10000000`. We should sanitize numbers by default so it always looks clean.

**Edit:** not an issue in Python, specifically a Formulas thing

**Comment by saraelsa** [comment]
I analyzed this issue. Here are my findings:

The value `1.1` is computed as `1.100000000000000088817841970012523233890533447265625` because the formula parsing engine internally uses `float` values instead of `BigDecimal` values. Most decimal numbers can't be represented exactly in base-2 which `float` uses so we get a small error. When the `float` is converted into a `BigDecimal` for use by the rest of the program, the error is then carried over.

This is the code that calculates the number of decimal places a field should be displayed with in the absence of a formatting rule specifying a certain precision:
```rs
let (_, exponent) = n.as_bigint_and_exponent();
let max_decimals = 9;
let decimals = exponent.min(max_decimals) as i16;

if is_percentage {
    Some(decimals - 2)
} else {
    Some(decimals)
}
```
(`quadratic-core/src/grid/sheet.rs`, `fn decimal_places`)

For the number above, with 51 decimal digits, it would return 9, the hardcoded maximum.

The desired return value for this function is 0. The following code can help do that:

```rs
let (_, exponent) = n.as_bigint_and_exponent();
let max_decimals = 9;

let (_, decimals) = n
    .with_scale_round(exponent.min(max_decimals) as i64, RoundingMode::HalfUp)
    .normalized()
    .as_bigint_and_exponent();

let decimals = decimals as i16;

if is_percentage {
    Some(decimals - 2)
} else {
    Some(decimals)
}
```
(`quadratic-core/src/grid/sheet.rs`, `fn decimal_places`, _proposed code_)

After rounding to `min(exponents, max_decimals)`, the code the number of decimal places the resulting decimal actually needs to take up and returns the value.

I tested the proposed code and it appears to work as expected with all tests passing.
