### ISSUE TITLE
Hitting the back button after creating a file causes infinite loading indication on the dashboard

### ISSUE THREAD

**Issue by ddimaria** [quadratichq/quadratic#1120]
Steps to reproduce:

1. From the dashboard, create a new individual file
2. After the file loads, hit the browser's back button
3. Dashboard is in loading mode.  No console or network errors.

<img width="649" alt="Screenshot 2024-02-23 at 11 03 45 AM" src="https://github.com/quadratichq/quadratic/assets/1536436/f8e32b16-bea1-4e16-91b7-6c8f44ce1aa0">

**Comment by jimniels** [comment]
This is a tricky one. I can't reproduce on `localhost` but I can with the preview branch.

I'm assuming this has something to do with how we changed from using a manual redirect to using `reloadDocument` from the react-router package. Both have their drawbacks.

Today in production, if you do this, you'll go back to where you were and the browser uses it's own cache to do this, so when you go back to "my files" the file you just created won't be there (because you went back in time to the page you were looking at, not back to the same URL but with updated data).

This seems to be working the same way, where hitting "back" takes you back to the page you were just at in its most recent state, which is a loading state (when you clicked "create", the dashboard part of the app went in to a loading state while it made a request to create a new page from the server, so that's really what you're navigating back to).

I'm not sure how to get around this, as it's a browser-level issue with how the back button works. Probably need to spend more time reading [this article on the bfcache](https://web.dev/articles/bfcache) and then figuring out the right fix

**Comment by luke-quadratic** [comment]
Can't repro in prod - plz reopen if someone experiences this
