### ISSUE TITLE
Right click behavior on header

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#136]
Should it be disabled on the header or have some other function?

<img width="295" alt="Screen Shot 2022-10-11 at 3 02 52 PM" src="https://user-images.githubusercontent.com/3479421/195197762-62f73c1a-800f-4402-8b5d-6097b068e99f.png">

**Comment by deshumake** [comment]
Excel has less options than a normal cell click, but they both have the current options. I'm enjoying being able to use all three functions on a col/row, so I think it's good as is now. Maybe keep them the same until there are more options in the cell context menu.

**Comment by jimniels** [comment]
Current functionality is that right click triggers the formatting menu for an individual cell:

<img width="511" alt="CleanShot 2023-05-17 at 14 01 01@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/f9c180dd-38f5-4f2b-b267-a78c1154fc8b">

And right clicking on a column selects the items in that column (and because it's a multi-selection, pops open the formatting menu)

<img width="530" alt="CleanShot 2023-05-17 at 14 01 13@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/dc8ec655-80bf-4995-8e28-188ad70ab6f2">

Going to close this issue as resolved for now. If we have issues with the functionality, we should open a separate issue and describe the problem as it exists in the app now.
