### ISSUE TITLE
Default numbers don't fit in cells

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1468]
![Image](https://github.com/quadratichq/quadratic/assets/146771258/d6521e23-eec0-4abe-aee7-bfc9c1feae0a)

**Comment by davidfig** [comment]
This is a bit complicated. We'll have to move the number rendering (ie, determining the what the string of the number looks like from its options and values) from Rust to TS, since we'll need to adjust how it's displayed based on its actual rendering size, which we can only calculate while rendering.

I started prototyping this work, but I'd rather wait until https://github.com/quadratichq/quadratic/pull/1406 (vertical wrapping) is merged, as I'l touch similar files to that one.
