### ISSUE TITLE
Zooming with ctrl+scrollwheel zooms in massive increments

### ISSUE THREAD

**Issue by murtaza64** [quadratichq/quadratic#152]
When I zoom in and out using ctrl+scroll (firefox, windows), the zoom jumps between very disparate levels (6%, 15%, 39%,  100%, 255%, 650%). It would be amazing if these changes were smoother so I could comfortably find a good zoom level using my scroll wheel as I do in many other apps (on webpages, firefox goes 10% at a time).

**Comment by davidkircos** [comment]
@davidfig Is this controlled by`pixi-viewport` ? Is it customizable?

**Comment by davidfig** [comment]
It might be customizable? What happens on ctrl + mouse? scroll, and what's the expected behavior?

**Comment by deshumake** [comment]
It's expected to scroll, it just does so by a huge amount right now

**Comment by deshumake** [comment]
I found a place where this can be fixed: line 44 of ViewportComponent.tsx.
```
44  |   .wheel({ trackpadPinch: true, wheelZoom: false, percent: 1.5 })
```
The "percent: 1.5" is what's causing this issue. Not sure what the actual lowest number can be, but going  down to 0 still scrolls, and changes the view percent to 46 when zooming out, and 218 when zooming in. (My mouse settings are supposed to scroll 3 lines on each click)

It seems like part of the issue is the original size of the spreadsheet behind it. Can we make it like 5x bigger? That would probably let us have more control over the amount we want to scroll by
