### ISSUE TITLE
Links to docs on all pages

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#801]
Make clearer buttons and links on all pages that link to docs and resources to get help, e.g. 

Files page
![stuff](https://github.com/quadratichq/quadratic/assets/146771258/e697419f-0af4-497b-b54b-ad73bbde0f10)

Sheet navbar (unbury docs/feedback from files)
![stuuff](https://github.com/quadratichq/quadratic/assets/146771258/7001e3a8-35d1-42f3-b849-434d75f5cb14)

**Comment by jimniels** [comment]
I'm hesitant to pepper this stuff throughout the app in different places — which is why it's not really in the dashboard yet. There's no consistent, repeatable place to reach for when you need help or want to provide feedback.

As a example, I like how Figma does this. They have a floating "?" menu that is in the app 

![CleanShot 2023-11-14 at 12 09 56@2x](https://github.com/quadratichq/quadratic/assets/1316441/a1231ed1-d572-484a-982d-92a3d03f27d8)

And on the dashboard

![CleanShot 2023-11-14 at 12 10 31@2x](https://github.com/quadratichq/quadratic/assets/1316441/9fed0c80-1612-4f15-9a07-beaf7d24247e)

They stuff a bunch of things in there

![CleanShot 2023-11-14 at 12 10 54@2x](https://github.com/quadratichq/quadratic/assets/1316441/6643059f-6ebb-4e17-91f1-0a502e00a2dc)

And they provide power users the ability to turn it off

![CleanShot 2023-11-14 at 12 11 21@2x](https://github.com/quadratichq/quadratic/assets/1316441/d91289d6-1a43-489f-8a21-6441dbca2a5c)

How we port that to our app in a way that makes sense to us, idk. But i'd like to give it a little more thought than "surface it more in both places" so there's more cohesion and consistency through the app when it comes to feedback/help.

Will give this more thought...
