### ISSUE TITLE
Cannot create or import a file with less that 1024px width

### ISSUE THREAD

**Issue by ddimaria** [quadratichq/quadratic#849]
At lower resolutions, the create and import buttons disappear.  They don't appear in the menu, so there is no way to create or import a file at those resolutions.

> 1024px
<img width="1105" alt="Screenshot 2023-11-20 at 12 03 46 PM" src="https://github.com/quadratichq/quadratic/assets/1536436/ddd3f027-7568-4aa3-9ed1-41c05f2ccad3">

< 1024px
<img width="1000" alt="Screenshot 2023-11-20 at 12 04 11 PM" src="https://github.com/quadratichq/quadratic/assets/1536436/2cd1aa7e-d325-45bd-9d33-877a5c1fe6ce">

**Comment by jimniels** [comment]
FWIW this was semi-intentional. The idea was don't allow people on mobile to create new files because, well, you don't do anything with them once you create them.

But given that desktop screens often get resized more narrow viewports, it makes sense to take a more careful approach than "make 'em disappear at screen size X"

**Comment by jimniels** [comment]
Create button is now visible across all sizes.
