### ISSUE TITLE
Giving focus to a cell allow browser-level zooming

### ISSUE THREAD

**Issue by ddimaria** [quadratichq/quadratic#900]
If you give a cell focus, then press cmd +, the browser zooms rather than the grid zooming.

**Comment by luke-quadratic** [comment]
https://github.com/quadratichq/quadratic/issues/537

reported behavior that should be confirmed to not exist/solved/decided isn't a concern as part of this issue: 
**No zoom when cursor in a cell**

To reproduce:

Double-click to edit a cell
Position the mouse cursor over the cell being edited
Scroll the mouse wheel to zoom in or out
Expected behavior: the sheet zooms as normal

Actual behavior: the sheet does not zoom

For comparison:

Excel doesn't allow ctrl+scroll to zoom at all when editing a cell
Sheets never allows ctrl+scroll to zoom, but when hovering over a cell I can trigger the browser's zoom (which is otherwise blocked)
