### ISSUE TITLE
Hitting escape while the code editor is out of focus should still close it

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#965]
Hey! Feature request I guess but I thought that `esc` while the code editor is open was broken a few times and I didn't realize it's because it doesn't do anything if the code editor is "out of focus"

"out of focus" happens for example if in the middle of coding i click on some other cells or edit their values. 

I would assume that hitting escape multiple times regardless of what's in focus should take you to the "default state" with the code editor closed. Can explain more if that doesn't make sense!

**Comment by luke-quadratic** [comment]
Makes sense. 

In theory there are occasions where you'd want that context to switch, e.g. when you open code editor but then move over to the sheet and start typing in another cell but hit escape to exit that cell - I think it'd be a bit jarring if that also closed the editor alongside the action of exiting editing that cell. 

I can imagine that if you've now clicked a cell that your context has now switched and the `esc` having no effect makes some sense (same situation with when you open menus, pressing `esc` closes the menu and shouldn't also close the editor); feel like that could potentially go either way since there are sheet actions that `esc` has an effect on, what do you think?

**Comment by N-Demir** [comment]
> In theory there are occasions where you'd want that context to switch, e.g. when you open code editor but then move over to the sheet and start typing in another cell but hit escape to exit that cell - I think it'd be a bit jarring if that also closed the editor alongside the action of exiting editing that cell.

Totally! In this case hitting `esc` once would exit that cell, hitting it again would close the editor

> (same situation with when you open menus, pressing esc closes the menu and shouldn't also close the editor)

and same thing in this scenario: first `esc` closes the menu, second closes the editor (or exits the cell if that's also happening)

> there are sheet actions that esc has an effect on

Oooo I did not realize that! What actions would those be and does that break this idea?
